project_id = "gzwjabvnoleqhfxzavuz"

[functions.fetch-shopify-orders]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.check-fraud]
verify_jwt = false

[functions.send-to-courier]
verify_jwt = false

[functions.courier-webhook]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false